### ISSUE TITLE
Feature Request: Rethink Epinio UI manifest workflow

### ISSUE THREAD

**Issue by mmartin24** [epinio/ui#222] opened 2023-04-17 10:45 UTC
### Is your feature request related to a problem?

During a demo it was proposed to rethink the workflow to the functioning of the manifest workflow from UI.
Currently an user that uploads a manifest can still change the type source. This behavior is different from using what is currently set in the manifest.

It could be discussed to have 2 different UI paths depending if a user selects the manifest path or a different one.

**Comment by enrichman** [comment] 2023-04-17 13:46
@richard-cox you're absolutely right, the issue was not probably clear enough. Let me try to explain it.

At the beginning when a user wants to create an application it's not clear that the manifest is a "shortcut" that will prefill or contains all the needed information. There is also a bug that will prevent the user on understand or change the "original source".

I was thinking to make this clearer just rearranging the UI of the first page in a way that the user will understand that to deploy an application it's enough to provide a manifest OR he can fill everything:

![Untitled-2023-02-22-1459](https://user-images.githubusercontent.com/1763949/232502569-093c93ad-fd58-4d66-8707-42ce70a2c5d1.png)

It will be also nice to get the YAML editor after the manifest upload, but it's a next enhancement.

**Comment by richard-cox** [comment] 2023-04-17 14:08
Ahh, i see.

In the Rancher Manager world for most resources we show an `Edit as YAML` option. Perhaps here we could have an alternative `Edit as Manifest` concept. Would need to think how that integrates with the wizard (we would always still need the last step).

**Comment by enrichman** [comment] 2023-04-17 14:32
I like the "wizard" name, maybe we can change this first page with

_Upload your application manifest or go through the wizard_ :mage:

The wizard button will just go through the current flow, but if the manifest was added or edited the fields will actually be already populated. Or maybe we can go directly to the summary page. The first option will be probably easier.

**Comment by richard-cox** [comment] 2023-04-19 13:19
Closing as duplicate of https://github.com/epinio/ui/issues/187

**Closed** 2023-04-21 09:04 UTC
Labels: kind/enhancement, area/ux
