### ISSUE TITLE
Deletion of two configurations together bound to an app fails

### ISSUE THREAD

**Issue by enrichman** [epinio/ui#196] opened 2022-09-14 09:27 UTC
**Describe the bug**
The deletion of two bounded configurations fails.

**To Reproduce**
1) Create an app
2) Create a config and bind it to the app
3) Create one more config and bind to the app
4) Delete both configs
5) One config is not going to be deleted and an error will occur (release already exists)

![Screenshot from 2022-09-14 11-19-43](https://user-images.githubusercontent.com/1763949/190116480-b06f2f70-83a1-41df-8176-7748f01f112f.png)

**Logs**
```json
{
    "errors": [
        {
            "status": 500,
            "title": "release: already exists",
            "details": "\nServer Backtrace: release: already exists\nhelm.sh/helm/v3/pkg/storage/driver.init\n\t/home/sles/go/pkg/mod/helm.sh/helm/v3@v3.9.4/pkg/storage/driver/driver.go:31\nruntime.doInit\n\t/home/sles/actions-runner/_work/_tool/go/1.18.5/x64/src/runtime/proc.go:6222\nruntime.doInit\n\t/home/sles/actions-runner/_work/_tool/go/1.18.5/x64/src/runtime/proc.go:6199\nruntime.doInit\n\t/home/sles/actions-runner/_work/_tool/go/1.18.5/x64/src/runtime/proc.go:6199\nruntime.doInit\n\t/home/sles/actions-runner/_work/_tool/go/1.18.5/x64/src/runtime/proc.go:6199\nruntime.doInit\n\t/home/sles/actions-runner/_work/_tool/go/1.18.5/x64/src/runtime/proc.go:6199\nruntime.doInit\n\t/home/sles/actions-runner/_work/_tool/go/1.18.5/x64/src/runtime/proc.go:6199\nruntime.doInit\n\t/home/sles/actions-runner/_work/_tool/go/1.18.5/x64/src/runtime/proc.go:6199\nruntime.doInit\n\t/home/sles/actions-runner/_work/_tool/go/1.18.5/x64/src/runtime/proc.go:6199\nruntime.doInit\n\t/home/sles/actions-runner/_work/_tool/go/1.18.5/x64/src/runtime/proc.go:6199\nruntime.doInit\n\t/home/sles/actions-runner/_work/_tool/go/1.18.5/x64/src/runtime/proc.go:6199\nruntime.doInit\n\t/home/sles/actions-runner/_work/_tool/go/1.18.5/x64/src/runtime/proc.go:6199\nruntime.doInit\n\t/home/sles/actions-runner/_work/_tool/go/1.18.5/x64/src/runtime/proc.go:6199\nruntime.main\n\t/home/sles/actions-runner/_work/_tool/go/1.18.5/x64/src/runtime/proc.go:233\nruntime.goexit\n\t/home/sles/actions-runner/_work/_tool/go/1.18.5/x64/src/runtime/asm_amd64.s:1571"
        }
    ]
}
```

```
Server Backtrace: release: already exists
helm.sh/helm/v3/pkg/storage/driver.init
    /home/sles/go/pkg/mod/helm.sh/helm/v3@v3.9.4/pkg/storage/driver/driver.go:31
runtime.doInit
    /home/sles/actions-runner/_work/_tool/go/1.18.5/x64/src/runtime/proc.go:6222
runtime.doInit
    /home/sles/actions-runner/_work/_tool/go/1.18.5/x64/src/runtime/proc.go:6199
runtime.doInit
    /home/sles/actions-runner/_work/_tool/go/1.18.5/x64/src/runtime/proc.go:6199
runtime.doInit
    /home/sles/actions-runner/_work/_tool/go/1.18.5/x64/src/runtime/proc.go:6199
runtime.doInit
    /home/sles/actions-runner/_work/_tool/go/1.18.5/x64/src/runtime/proc.go:6199
runtime.doInit
    /home/sles/actions-runner/_work/_tool/go/1.18.5/x64/src/runtime/proc.go:6199
runtime.doInit
    /home/sles/actions-runner/_work/_tool/go/1.18.5/x64/src/runtime/proc.go:6199
runtime.doInit
    /home/sles/actions-runner/_work/_tool/go/1.18.5/x64/src/runtime/proc.go:6199
runtime.doInit
    /home/sles/actions-runner/_work/_tool/go/1.18.5/x64/src/runtime/proc.go:6199
runtime.doInit
    /home/sles/actions-runner/_work/_tool/go/1.18.5/x64/src/runtime/proc.go:6199
runtime.doInit
    /home/sles/actions-runner/_work/_tool/go/1.18.5/x64/src/runtime/proc.go:6199
runtime.doInit
    /home/sles/actions-runner/_work/_tool/go/1.18.5/x64/src/runtime/proc.go:6199
runtime.main
    /home/sles/actions-runner/_work/_tool/go/1.18.5/x64/src/runtime/proc.go:233
runtime.goexit
    /home/sles/actions-runner/_work/_tool/go/1.18.5/x64/src/runtime/asm_amd64.s:1571

```

**Comment by mmartin24** [comment] 2023-03-08 15:27
FTR:
confirmed with @richard-cox the issue [above](https://github.com/epinio/ui/issues/196#issuecomment-1460318528) and moved this item into `epinio/ui` planning to be tackled there. 
CC: @scures it is assigned to you ok?

**Comment by mmartin24** [comment] 2023-03-08 16:02
@scures interestingly I cannot reproduce either now. Not sure if I had something cached when I encountered the issue.
I will try a bit more and if I can't I will just close the issue.

**Closed** 2023-03-09 09:03 UTC
Labels: kind/bug
