### ISSUE TITLE
[UI] - Epinio welcome screen does not show up if a namespace exists

### ISSUE THREAD

**Issue by juadk** [epinio/ui#132] opened 2022-06-10 07:53 UTC
The new welcome screen only appears when there is no namespace created and by default, there is one. 
Users will never see it because we create the workspace namespace by default.
I had to delete it to see the welcome screen.

- Without existing namespace:
![image](https://user-images.githubusercontent.com/6025636/173017649-d31773ff-db58-43c4-ac09-ce7894e42062.png)

- With a namespace, you land on:
![image](https://user-images.githubusercontent.com/6025636/173017889-b15623ee-3318-4ae2-a6b3-7979383cf808.png)

**Comment by richard-cox** [comment] 2022-06-10 08:26
Only showing the welcome screen when there are no namespaces is by design. It's primarily meant to guide new users through the initial process so they're not lost knowing they have to create a namespace first.

This broke down though when the new default user is already assigned to the default namespace.

It would be an improvement to have a proper landing page (rather than replacing the content of the application list). If we work out the user is new then show appropriate messaging (so taking into account their namespaces). If not we show general info about the cluster, stats, etc.

**Comment by richard-cox** [comment] 2022-10-05 14:35
Discussed with Sorin. This could be a candidate to add to a new landing/home page where we could expand on the concept of helping initial users getting started with Epinio

**Comment by mmartin24** [comment] 2023-02-13 13:34
@scures / @richard-cox , I created a dedicated testing ticket for the new functionalities
I posted [there](https://github.com/epinio/epinio-end-to-end-tests/issues/296#issuecomment-1427940082) what I checked in detail and several questions about functionality with videos and screenshots for clarity. It would be great if you could take a look at these. As summary :

1. Default page when the user logs in seems still pointing to `Applications`, not the new `Dashboard` one. Is  this expected?
2. When all namespaces are deleted, the `Namespace` card is blank with spinning wheel in it. Is this expected? 
3.  There is no `Configuration` card/block as there is for Namespaces, Applications or Services. Is this expected?
4. As more namespaces are added, they are listed in the `Namespace` card, but this does not occur for for `Applications` and `Services`. Is this expected?

**Comment by mmartin24** [comment] 2023-02-15 09:22
Fixed with the new dashboard page. 
Issues above have been addressed here: https://github.com/epinio/epinio-end-to-end-tests/issues/296

**Closed by mmartin24** 2023-02-15 09:22 UTC
Labels: kind/enhancement, epinio-ui-v1.5.1+
