### ISSUE TITLE
[UI] Create applications from manifest file provides wrong application source type

### ISSUE THREAD

**Issue by torchiaf** [epinio/ui#235] opened 2023-05-17 08:34 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Applications can be exported as manifest file, which contains source information.
The generated file can be used to create a new instance of the application. 
At the moment, applications with source type 'GitHub' are imported as 'GitUrl' applications. This is reflected also to the form fields.

- ToDo, upload screenshots.

### Expected Behavior

The source type should be 'GitHub'

### Steps To Reproduce

- Create a GitHub application
- Export application's manifest
- Import the application from manifest

### Environment

```markdown
- OS:
- Architecture:
- Epinio Version:
- Cluster:
  - Provider:
  - Options:
  - Kubernetes Version:
```

**Comment by mmartin24** [comment] 2023-05-23 16:39
This seems duplicate of https://github.com/epinio/ui/issues/226
Tested anyhow with github manifest as below as well and working in latest epinio-dev:

```json
{"name":"github-app","configuration":{"instances":1,"configurations":[],"environment":{},"routes":["github-app.172.19.0.3.omg.howdoi.website"],"appchart":"standard"},"origin":{"Kind":2,"git":{"revision":"e84b2a73b2c1bb88d9cdc99ffca1a3d05b3d261b","repository":"https://github.com/epinio/example-go","provider":"github","branch":"main"}}}
```

**Closed by mmartin24** 2023-05-23 16:39 UTC
Labels: kind/bug
