### ISSUE TITLE
[UI] Support disabling of Dex

### ISSUE THREAD

**Issue by richard-cox** [epinio/ui#176] opened 2023-01-09 10:53 UTC
See https://github.com/epinio/helm-charts/issues/325

The UI assumes Dex will always be enabled. Need to ensure the helm chart value makes it's way to the ui-backend and disables the auth provider

**Comment by mmartin24** [comment] 2023-02-21 15:23
@richard-cox I was unsure how to test this so just wanted to share what I tried and results.


1- I tried to disable dex from `/chart/epinio/values.yaml`:
https://github.com/epinio/helm-charts/blob/main/chart/epinio/values.yaml#L167-L168

This will not allow epinio to be deployed and will end up with the pod epinio-ui in status `CreateContainerConfigError`

![image](https://user-images.githubusercontent.com/37271841/220382477-7a2c2ae2-f5cf-4a05-9607-f1a460c5c961.png)

Can you confirm if this is an error? When I tested [here](https://github.com/epinio/epinio/pull/1995#issuecomment-1379049983) before the UI integration I was able to deploy Epinio. 


2 - I attempted to disable solely from `helm-charts/chart/epinio-ui/values.yaml` (leaving the one on  `/chart/epinio/values.yaml` as true):
https://github.com/epinio/helm-charts/blob/6451a4764cf11c3cd51f2b86260f9d93a8b843ca/chart/epinio-ui/values.yaml#L27-28

This does not seemed to have effect and DEX is being displayed.
![image](https://user-images.githubusercontent.com/37271841/220386150-3d431e76-7453-4630-9c37-5ca5ed5e9adc.png)


Can you please let me know if any of the tests above is valid / how to check this?

Thanks

**Comment by thehejik** [comment] 2023-02-22 08:39
Just checked what Manuel did and it seems the problem is that `epinio-ui` pod is unable to start due to missing `dex-config`.

Epinio deployed with `--set global.dex.enabled=false`. This is valid option from values.yaml and it should work.

```
$ kubectl describe pod epinio-ui-7c74cb88dd-7xnwz -n epinio
...
  Normal   Pulled     4s (x5 over 32s)  kubelet            Container image "ghcr.io/epinio/epinio-ui:v1.7.0-0.0.2" already present on machine
  Warning  Failed     4s (x5 over 32s)  kubelet            Error: secret "dex-config" not found
```

**Comment by mmartin24** [comment] 2023-02-22 10:24
FTR: this item seems not working at the moment. Opened momentarily https://github.com/epinio/epinio/issues/2094 for fixing it. Once determined if the nature of the fix is backend or ui it can be decided if transfer the issue here.

**Comment by mmartin24** [comment] 2023-02-22 12:50
This issue seems fixed in [Fixed epinio-ui deployment with disabled dex epinio/helm-charts#378](https://github.com/epinio/helm-charts/pull/378)
Test steps and fix proof there: https://github.com/epinio/helm-charts/pull/378#issuecomment-1439956709

![2023-02-22_13-41](https://user-images.githubusercontent.com/37271841/220623907-a670887d-ceab-45c7-90ec-d97991aebfcc.png)

**Closed** 2023-02-22 13:35 UTC
Labels: area/backend, epinio-ui-v1.5.1+, area/dex
